"""init db

Revision ID: b38cdb8e0489
Revises: 
Create Date: 2024-06-05 13:36:27.296811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b38cdb8e0489'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table('authors',
                    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
                    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('birthdate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
                    sa.Column('biography', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='authors_pkey'),
                    postgresql_ignore_search_path=False
                    )
    op.create_table('books',
                    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
                    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('author_id', sa.UUID(), autoincrement=False, nullable=True),
                    sa.Column('published_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
                    sa.Column('summary', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], name='books_author_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name='books_pkey')
                    )
    op.create_table('cookies',
                    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
                    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='cookies_pkey')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table('books')
    op.drop_table('authors')
    op.drop_table('cookies')
# ### commands auto generated by Alembic - please adjust! ###
